---
image:
  tag: latest

persistence:
  enabled: true
  size: 8Gi

ingress: 
  enabled: true
  hosts: 
  - "test-grafana.sohan.cloud"

securityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

deploymentStrategy:
  type: Recreate
