---
image:
  tag: latest

persistence:
  enabled: true
  size: 8Gi

service:
  enabled: true
  type: NodePort

ingress: 
  enabled: false

securityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

deploymentStrategy:
  type: Recreate
