{
 "title": "Test Dashboard Simple",
 "description": "Dashboard to view multiple servers",
 "tags": [ "IB" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_exporter_build_info, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",node=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"system\",node=~'$node'}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",node=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"user\",node=~'$node'}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",node=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"nice\",node=~'$node'}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",node=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"iowait\",node=~'$node'}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",node=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"steal\",node=~'$node'}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",node=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"idle\",node=~'$node'}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",node=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"irq\",node=~'$node'}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",node=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"softirq\",node=~'$node'}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\",node=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"guest\",node=~'$node'}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "repeat": "node",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{node=~'$node'} - node_memory_MemFree_bytes{node=~'$node'} - node_memory_Buffers_bytes{node=~'$node'} - node_memory_Cached_bytes{node=~'$node'} - node_memory_SwapCached_bytes{node=~'$node'} - node_memory_Slab_bytes{node=~'$node'} - node_memory_PageTables_bytes{node=~'$node'} - node_memory_VmallocUsed_bytes{node=~'$node'} ) or ( node_memory_MemTotal{node=~'$node'} - node_memory_MemFree{node=~'$node'} - node_memory_Buffers{node=~'$node'} - node_memory_Cached{node=~'$node'} - node_memory_SwapCached{node=~'$node'} - node_memory_Slab{node=~'$node'} - node_memory_PageTables{node=~'$node'} - node_memory_VmallocUsed{node=~'$node'} )",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{node=~'$node'} or node_memory_Buffers{node=~'$node'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{node=~'$node'} or node_memory_Cached{node=~'$node'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=~'$node'} or node_memory_MemFree{node=~'$node'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Slab_bytes{node=~'$node'} or node_memory_Slab{node=~'$node'}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_SwapCached_bytes{node=~'$node'} or node_memory_SwapCached{node=~'$node'}",
     "legendFormat": "SwapCached"
    },
    {
     "expr": "node_memory_PageTables_bytes{node=~'$node'} or node_memory_PageTables{node=~'$node'}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{node=~'$node'} or node_memory_VmallocUsed{node=~'$node'}",
     "legendFormat": "VmallocUsed"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{node=~'$node'} - node_memory_SwapFree{node=~'$node'}) or (node_memory_SwapTotal{node=~'$node'} - node_memory_SwapFree{node=~'$node'})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_Committed_AS_bytes{node=~'$node'} or node_memory_Committed_AS{node=~'$node'}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_Mapped_bytes{node=~'$node'} or node_memory_Mapped{node=~'$node'}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_Active_bytes{node=~'$node'} or node_memory_Active{node=~'$node'}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Inactive_bytes{node=~'$node'} or node_memory_Inactive{node=~'$node'}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "repeat": "node",
   "yaxes": [
    {
     "format": "bps",
     "label": "bits/second in (-) / bits out (+)"
    }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{node=~'$node'}[5m])*8 or irate(node_network_receive_bytes{node=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{node=~'$node'}[5m])*8 or irate(node_network_transmit_bytes{node=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "InfiniBand Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "repeat": "node",
   "yaxes": [
    {
     "format": "bps",
     "label": "bits/second in (-) / bits out (+)"
    }
   ],
   "targets": [
    {
     "expr": "irate(node_infiniband_port_data_received_bytes_total{node=~\"$node\",device!~\"hfi.+\"}[5m])*8 or irate(node_infiniband_port_data_received_bytes_total{node=~\"$node\",device=~\"hfi.+\"}[5m])*8*2",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_infiniband_port_data_transmitted_bytes_total{node=~\"$node\",device!~\"hfi.+\"}[5m])*8 or irate(node_infiniband_port_data_transmitted_bytes_total{node=~\"$node\",device=~\"hfi.+\"}[5m])*8*2",
     "legendFormat": "{{device}}_out"
    }
   ]
  }
 ]
}